adoption/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

app_name = "adoption"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("apps.home.urls")),
    path('animals/', include("apps.animals.urls")),
    path('accounts/', include("apps.accounts.urls")),
    path('messages/', include('apps.django_messages.urls')),
    # path('adopt/', include('requestadopt.urls')), # what is this?
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include
from .views import signup, Profile, ProfileDetailView, ProfileUpdate, UserList, ProfileDetail, user_profile

app_name = "accounts"
urlpatterns = [

    path('users/', UserList.as_view(template_name="accounts/user_list.html", ), name="user_list"),
    path('login/', LoginView.as_view(template_name="accounts/login.html", ), name="login"),
    path('logout/', LogoutView.as_view(template_name='accounts/logout.html'), name="logout"),
    path('register/', signup, name="register"),
    # path('<nickname>', user_profile, name = 'profile'),
    path('<nickname>/update/', ProfileUpdate.as_view(), name='update'),
    path('<nickname>', user_profile, name='detail'),
    # path('messages/',include(django_messages_urls), name = 'messages')

]

apps/animals/urls.py
from django.urls import path
from .views import (AnimalCreateView, AnimalListView, AnimalDetailView, AnimalUpdateView, MyAnimalsListView,
                    AnimalDeleteView, add_comment_to_post)

app_name = "animals"

urlpatterns = [
    path('animals/', AnimalListView.as_view(), name= "list" ),
    path('create/', AnimalCreateView.as_view(success_url="/animals/"), name="create"),
    path('mylist/', MyAnimalsListView.as_view(model="Animals"), name="list_animals"),
    path('<slug>/update/', AnimalUpdateView.as_view(model="Animals", success_url="/animals/mylist/"), name="update"),
    path('<slug>/delete/', AnimalDeleteView.as_view(), name="delete"),

    path('<slug>/', AnimalDetailView.as_view(), name="detail"),
    # path('myanimals/', MyAnimalsListView.as_view(model = "Animals"), name="mylist"),
    path('', AnimalListView.as_view(), name='list'),
    path('post/<slug>/comment/', add_comment_to_post, name='add_comment_to_post')
]

apps/django_messages/urls.py
from django.conf.urls import *
from django.views.generic import RedirectView
from django.urls import path, include

from .views import *

app_name = "messages"

urlpatterns = (
    path('', RedirectView.as_view(permanent=True, url='inbox/'), name='messages_redirect'),
    path('inbox/', inbox, name='messages_inbox'),
    path('outbox/', outbox, name='messages_outbox'),
    path('compose/', compose, name='messages_compose'),
    path('compose/<recipient>/', compose, name='messages_compose_to'),
    path('reply/(<message_id>/', reply, name='messages_reply'),
    path('view/(<message_id>/', view, name='messages_detail'),
    path('delete/(<message_id>)/', delete, name='messages_delete'),
    path('undelete/(<message_id>)/', undelete, name='messages_undelete'),
    path('trash/', trash, name='messages_trash'),
)

apps/animals/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
import datetime
from django.db.models.signals import pre_save, post_save
from .utils import unique_slug_generator
from django.shortcuts import get_object_or_404
from ..accounts.models import UserModel


class Animals(models.Model):
    DOG = "dog"
    CAT = "cat"
    MALE = "m"
    FEMALE = "f"

    ANIMAL_CHOICES = (
        (DOG, 'Dog'),
        (CAT, 'Cat'),
        
    )

    GENDER_CHOICES = (

        (MALE, "Male"),
        (FEMALE, "Female")

    )

    category = models.CharField(max_length=10, choices=ANIMAL_CHOICES, default=DOG)
    name = models.CharField(max_length=120, null=False, blank=False)
    location = models.CharField(max_length=120, null=False, blank=False)
    sex = models.CharField(choices=GENDER_CHOICES, max_length=120, null=False, blank=False)
    description = models.TextField(max_length=120, null=False, blank=False)
    photo = models.ImageField("photo", upload_to="media/", null=False, blank=False)
    timestamp = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(null=True, blank=True)
    author = models.ForeignKey(UserModel, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    @property
    def title(self):
        return self.name


def animal_pre_save_receiver(sender, instance, *args, **kwargs):
    print("saving")
    print(instance.timestamp)
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)


# def animal_post_save_receiver(sender, instance, created, *args, **kwargs):
# 		print("saved")
# 		print(instance.timestamp)


pre_save.connect(animal_pre_save_receiver, sender=Animals)


# post_save.connect(animal_post_save_receiver,  sender= Animals)


class Comment(models.Model):
    text = models.TextField(max_length=300, blank=False, null=False)
    post = models.ForeignKey('animals.Animals', related_name='comments', on_delete=models.CASCADE)
    author = models.ForeignKey("accounts.UserModel", on_delete=models.CASCADE, default=1)
    created_date = models.DateTimeField(auto_now_add=True)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.text

apps/animals/forms.py
from django import forms
from .models import Animals, Comment


# class AnimalCreate(forms.Form):

# 	name            = forms.CharField()
# 	breed           = forms.CharField()
# 	age             = forms.CharField()
# 	gender          = forms.CharField()





class AnimalCreateForm(forms.ModelForm):
	# category = forms.CharField(required= False, validators=[validate_category])
	# email = forms.EmailFi.eld()
	
	class Meta:
		model = Animals
		fields =[
		"category", 
		"name", 
		"location",
		"sex",
		"description",
		"photo",
		
		
		
		
		
		]


class CommentForm(forms.ModelForm):
	# text = TextField(max_length = 240, blank = False, null = False, default = "o")

	class Meta:
		model = Comment
		fields = ( 'text',)

apps/animals/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.template import loader
from django.http import HttpResponse
from django.views.generic import (View, ListView, DetailView, UpdateView, DeleteView, TemplateView, CreateView)
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import AnimalCreateForm
from .models import Animals, Comment
from django.urls import reverse_lazy
from django.db.models import Q
from django.views.generic.edit import FormView
from django.contrib.auth import get_user_model
from django.contrib.messages.views import SuccessMessageMixin
from .forms import CommentForm
from ..accounts.models import UserModel
from django.contrib import messages

User = get_user_model()


def add_comment_to_post(request, slug):
    template_name = "comment.html"
    post = get_object_or_404(Animals, slug=slug)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.author = request.user
            comment.save()
            messages.success(request, 'Comment succesufuly added!')
            return redirect("/home/")
    else:
        form = CommentForm()
    return render(request, template_name, {'form': form})


class AnimalCreateView(SuccessMessageMixin, FormView, LoginRequiredMixin, CreateView):
    form_class = AnimalCreateForm
    template_name = 'animals/form.html'
    success_message = 'You succesufuly added animal for adoption!'
    model = Animals

    # def get_succes_message(self, cleaned_data):
    #     print(cleaned_data)
    #     return ("You added animal succesufuly!")

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.author = self.request.user
        return super(AnimalCreateView, self).form_valid(form)

    # def form_valid(self, form):
    #     instance = form.save(commit=False)
    #     instance.user = self.request.user
    #     return super(AnimalCreateView, self).form_valid(form)


class AnimalListView(LoginRequiredMixin, ListView):
    template_name = "animals/animal_list.html"

    def get_queryset(self):
        return Animals.objects.all()


class MyAnimalsListView(LoginRequiredMixin, ListView):
    context_object_name = "animal_list"
    template_name = "animals/my_animal_list.html"

    # queryset = Animals.objects.filter(autor = request.User)
    def get_queryset(self):
        return Animals.objects.filter(author=self.request.user)


class AnimalDetailView(LoginRequiredMixin, DetailView):
    template_name = "animals/animals_detail.html"
    model = Animals

    def get_context_data(self, *args, **kwargs):
        context = super(AnimalDetailView, self).get_context_data(*args, **kwargs)
        print(context)
        # context['object'] = UserModel.objects.all(nickname = nickname)
        return context


class AnimalUpdateView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    form_class = AnimalCreateForm
    login_url = '/accounts/login/'
    template_name = 'animals/animals_update.html'
    success_message = 'You succesufuly updated your pet!'
    success_url = "/animals/mylist/"

    # success_url = "/restaurants/"

    def get_context_data(self, *args, **kwargs):
        context = super(AnimalUpdateView, self).get_context_data(*args, **kwargs)
        name = self.get_object().name
        context['title'] = f'Update animal: {name}'
        return context

    def get_queryset(self):
        return Animals.objects.filter(author=self.request.user)


class AnimalDeleteView(SuccessMessageMixin, LoginRequiredMixin, DeleteView):
    template_name = "animals/author_check_delete.html"
    model = Animals
    success_message = "You succesufuly removed animal"
    success_url = reverse_lazy("animals:list_animals")

templates/animals/snippets/form_snippet.html
{% if form.errors.non_field_errors %}
{{ form.errors.non_field_errors }}
{% endif %}
<form enctype="multipart/form-data" method='POST'> {% csrf_token %}
    {{ form.as_p }}
    <button type='submit'>Save</button>
</form>

templates/animals/snippets/login_form.html
{% block content %}

{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

{% if next %}
    {% if user.is_authenticated %}
    <p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
    {% else %}
    <p>Please login to see this page.</p>
    {% endif %}
{% endif %}

<form method="post" action="{% url 'login' %}">
{% csrf_token %}
<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
</tr>
</table>

<input type="submit" value="login" />
<input type="hidden" name="next" value="{{ next }}" />
</form>

{# Assumes you setup the password_reset view in your URLconf #}


{% endblock %}

templates/animals/snippets/nav.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

<style> 
h1 { color: orange; }
.navbar {
  overflow: hidden;
  background-color: #333;
  font-family: Arial;
}
</style>

<nav class="navbar navbar-dark bg-dark">
<div class="container" align="center"> <a href="{% url 'index' %}"><h1>Adopt.me</h1></a>
{% if user.is_authenticated %}
    <a href="{% url 'home' %}">Home</a>
    <a href="{% url 'animals:create' %}">Add animal</a>
    <a href="{% url 'messages:messages_redirect' %}">Messages</a>
    <a href="{% url 'accounts:user_list' %}">Members</a>
    <a href="{% url 'accounts:detail' nickname=request.user.nickname %}">My profile</a>
    <a href="{% url 'accounts:logout' %}">Logout</a>
{% endif %}
</div>
</nav>
</div>

templates/animals/snippets/search.html
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
body {
    font-family: Arial;
}

* {
    box-sizing: border-box;
}

form.example input[type=text] {
    padding: 10px;
    font-size: 17px;
    border: 1px solid grey;
    float: left;
    width: 80%;
    background: #f1f1f1;
}

form.example button {
    float: left;
    width: 20%;
    padding: 10px;
    background: #2196F3;
    color: white;
    font-size: 17px;
    border: 1px solid grey;
    border-left: none;
    cursor: pointer;
}

form.example button:hover {
    background: #0b7dda;
}

form.example::after {
    content: "";
    clear: both;
    display: table;
}
</style>
</head>
<body>

<h2>Search for a pet</h2>
<form class="example" action="/action_page.php">
  <input type="text" placeholder="Search.." name="search">
  <button type="submit"><i class="fa fa-search"></i></button>
</form>