adoption/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

app_name = "adoption"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("apps.home.urls")),
    path('animals/', include("apps.animals.urls")),
    path('accounts/', include("apps.accounts.urls")),
    path('messages/', include('apps.django_messages.urls')),
    # path('adopt/', include('requestadopt.urls')), # what is this?
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include
from .views import signup, Profile, ProfileDetailView, ProfileUpdate, UserList, ProfileDetail, user_profile

app_name = "accounts"
urlpatterns = [

    path('users/', UserList.as_view(template_name="accounts/user_list.html", ), name="user_list"),
    path('login/', LoginView.as_view(template_name="accounts/login.html", ), name="login"),
    path('logout/', LogoutView.as_view(template_name='accounts/logout.html'), name="logout"),
    path('register/', signup, name="register"),
    # path('<nickname>', user_profile, name = 'profile'),
    path('<nickname>/update/', ProfileUpdate.as_view(), name='update'),
    path('<nickname>', user_profile, name='detail'),
    # path('messages/',include(django_messages_urls), name = 'messages')

]

apps/animals/urls.py
from django.urls import path
from .views import (AnimalCreateView, AnimalListView, AnimalDetailView, AnimalUpdateView, MyAnimalsListView,
                    AnimalDeleteView, add_comment_to_post)

app_name = "animals"

urlpatterns = [
    path('animals/', AnimalListView.as_view(), name= "list" ),
    path('create/', AnimalCreateView.as_view(success_url="/animals/"), name="create"),
    path('mylist/', MyAnimalsListView.as_view(model="Animals"), name="list_animals"),
    path('<slug>/update/', AnimalUpdateView.as_view(model="Animals", success_url="/animals/mylist/"), name="update"),
    path('<slug>/delete/', AnimalDeleteView.as_view(), name="delete"),

    path('<slug>/', AnimalDetailView.as_view(), name="detail"),
    # path('myanimals/', MyAnimalsListView.as_view(model = "Animals"), name="mylist"),
    path('', AnimalListView.as_view(), name='list'),
    path('post/<slug>/comment/', add_comment_to_post, name='add_comment_to_post')
]

apps/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
 
 
 
class MyUserManager(BaseUserManager):
    use_in_migrations = True
    
    
    # python manage.py createsuperuser
    def create_superuser(self, email, is_staff, password):
        user = self.model(
                          email = email,                         
                          is_staff = is_staff,
                          )
        user.set_password(password)
        user.save(using=self._db)
        return user
 
class UserModel(AbstractBaseUser):
    sys_id = models.AutoField(primary_key=True, blank=True)
    nickname = models.CharField(max_length = 17, blank = False, null= False)
    location = models.CharField(max_length = 17, blank = False, null= False)
    first_name = models.CharField(max_length = 255, blank= False, null = False)
    last_name = models.CharField(max_length = 255, blank= False, null = False)       
    email = models.EmailField(max_length=127, unique=True, null=False, blank=False)
    is_staff = models.BooleanField(default = False)
    is_active = models.BooleanField(default=True)
    slug = models.SlugField(null = True, blank = True)
    
 
 
    objects = MyUserManager()
 
    USERNAME_FIELD = "email"
    # REQUIRED_FIELDS must contain all required fields on your User model, 
    # but should not contain the USERNAME_FIELD or password as these fields will always be prompted for.
    REQUIRED_FIELDS = ['is_staff']
 
    class Meta:
        app_label = "accounts"
        db_table = "users"
 
    def __str__(self):
        return self.email


    def get_full_name(self):
        """
        Returns the first_name plus the last_name, with a space in between.
        """
        full_name = '%s %s' %(self.first_name, self.last_name)
        return full_name.strip()

 
    
    def get_username(self):
        return self.email
 
    def get_short_name(self):
        return self.first_name + self.last_name
 
 
    # this methods are require to login super user from admin panel
    def has_perm(self, perm, obj=None):
        return self.is_staff
 
    # this methods are require to login super user from admin panel
    def has_module_perms(self, app_label):
        return self.is_staff

apps/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import UserModel
from django.views.generic.edit import UpdateView



class SignUpForm(UserCreationForm):
   
    # email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = UserModel
        fields = ( 'nickname', 'first_name', 'last_name', "location",'email', 'password1', 'password2')


class UpdateProfile(forms.ModelForm):
	
	
	
	class Meta:
		model = UserModel
		fields = ( 'nickname', 'first_name', 'last_name', "location")

apps/accounts/views.py
from django.contrib.auth import login, authenticate
from django.http import Http404
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import View, CreateView, DetailView, FormView, UpdateView, ListView
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.urls import reverse_lazy
from .forms import SignUpForm, UpdateProfile
from .models import UserModel
from django.views.generic.detail import SingleObjectMixin
from django.contrib.auth import logout, login
from ..animals.models import Animals


class Profile(SingleObjectMixin):
    model = UserModel

    def get_object(self):
        try:
            return self.request.user.get_profile()
            # return queryset.get_profile()
        except self.model.DoesNotExist:
            raise NotImplemented(" note implemented user")


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            # username = form.cleaned_data.get('username')
            # raw_password = form.cleaned_data.get('password1')
            # user = authenticate(username=username, password=raw_password,)
            login(request, user, backend='django.contrib.auth.backends.ModelBackend')
            return redirect('home')
    else:
        form = SignUpForm()
    return render(request, 'accounts/signup.html', {'form': form})


def user_profile(request, nickname):
    template_name = "accounts/profile.html"

    # user = UserModel.objects.get(nickname=nickname) # it is wrong or using filter
    user = get_object_or_404(UserModel, nickname=nickname)
    animals = Animals.objects.filter(author=user)
    context = {"user": user, "animals": animals}
    return render(request, template_name, context)


class UserList(ListView):
    def get_queryset(self):
        return UserModel.objects.all()


class ProfileDetail(DetailView):
    template_name = "accounts/profile.html"

    model = UserModel

    def get_context_data(self, *args, **kwargs):
        context = super(ProfileDetail, self).get_context_data(*args, **kwargs)
        print(context)

        return context


class ProfileUpdate(SuccessMessageMixin, FormView, LoginRequiredMixin, UpdateView):
    template_name = "accounts/profile_update.html"
    model = UserModel
    succes_message = "Profile Updated!"
    form_class = UpdateProfile

    # fields = ["nickname", "first_name", "last_name"]

    def get_object(self, queryset=None):
        user = UserModel.objects.get(nickname=self.kwargs["nickname"])
        return user

    def get_success_url(self):
        # succes_url = "/accounts/<nickname>"
        return reverse_lazy("home")


class ProfileDetailView(DetailView):
    template_name = "accounts/profile.html"

    def get_object(self):
        nickname = self.kwargs.get("nickname")
        if nickname is None:
            raise Http404
        return get_object_or_404(UserModel, nickname__iexact=nickname, is_active=True)

templates/accounts/login.html
{% include 'base.html' %}

 <div align="center" > <h1>Login</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form> </div>


	

templates/accounts/logout.html
{% include "base.html" %}

{% block content %}


<h2 align="center"> Yoi are now logged out! </h2>

 <div align="center" > <h1>Login again?</h1>


<a href="{% url 'accounts:login' %}">LOGIN</a>

 	</div>
  <!-- <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form> </div> -->
{% endblock %}

templates/accounts/profile.html
{% include "base.html" %}
{% block content%}

<div class="container"> <h2> User Info: </h2>
<ul>

<li>Nickname: {{ user.nickname }}</li>
<li>First name: {{ user.first_name }}</li>
<li>Last Name: {{ user.last_name }}</li>
<li>Location: {{ user.location }}</li>
<li> Animals added: {{ animals|length }}</li>
{% if user.is_authenticated and request.user == user %}
<a href="{% url 'accounts:update' nickname=user.nickname %}"> Edit profile</a> 
{% endif %}

</ul>
<h3> User animals: </h3>
<ul>
{% for obj in animals %}

<a href="{% url 'animals:detail' slug=obj.slug %}"><li>{{ obj.name }}, <small>{{ obj.category }}</small></li> </a>

{% empty %}
<p> User didnt add any animal for adoption. </p>
{% endfor %}
</ul>
</div>
{% endblock %}

templates/accounts/profile_update.html
{% include "base.html" %}
{% if messages %}
<div class="alert alert-success">
    {% for m in messages %}
    <li>{{ m }}</li> <br>
    {% endfor %}
</div>
{% endif %}


<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
     <button type="submit" value="Submit">Submit</button>
  <button type="reset" value="Reset">Reset</button> <br> or <br>
  <a href="{% url 'accounts:detail' nickname=user.nickname %}"> Back to profile </a>
</form>

templates/accounts/signup.html
{% include 'base.html' %}



{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}

templates/accounts/user_list.html
{% include "base.html" %}

{% block content %}
<div class="container">
<h2> List of registered users: </h2>

{% for object in object_list %}
<ul>

<li> <a href="{% url 'accounts:detail' nickname=object.nickname %}"> {{ object.nickname}} </a> <small>Last login: {{ object.last_login }}</small>  </li>

</ul>
{% endfor %}

</div>



{% endblock content %}