adoption/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

app_name = "adoption"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("apps.home.urls")),
    path('animals/', include("apps.animals.urls")),
    path('accounts/', include("apps.accounts.urls")),
    path('messages/', include('apps.django_messages.urls')),
    # path('adopt/', include('requestadopt.urls')), # what is this?
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include
from .views import signup, Profile, ProfileDetailView, ProfileUpdate, UserList, ProfileDetail, user_profile

app_name = "accounts"
urlpatterns = [

    path('users/', UserList.as_view(template_name="accounts/user_list.html", ), name="user_list"),
    path('login/', LoginView.as_view(template_name="accounts/login.html", ), name="login"),
    path('logout/', LogoutView.as_view(template_name='accounts/logout.html'), name="logout"),
    path('register/', signup, name="register"),
    # path('<nickname>', user_profile, name = 'profile'),
    path('<nickname>/update/', ProfileUpdate.as_view(), name='update'),
    path('<nickname>', user_profile, name='detail'),
    # path('messages/',include(django_messages_urls), name = 'messages')

]

apps/animals/urls.py
from django.urls import path
from .views import (AnimalCreateView, AnimalListView, AnimalDetailView, AnimalUpdateView, MyAnimalsListView,
                    AnimalDeleteView, add_comment_to_post)

app_name = "animals"

urlpatterns = [
    path('animals/', AnimalListView.as_view(), name= "list" ),
    path('create/', AnimalCreateView.as_view(success_url="/animals/"), name="create"),
    path('mylist/', MyAnimalsListView.as_view(model="Animals"), name="list_animals"),
    path('<slug>/update/', AnimalUpdateView.as_view(model="Animals", success_url="/animals/mylist/"), name="update"),
    path('<slug>/delete/', AnimalDeleteView.as_view(), name="delete"),

    path('<slug>/', AnimalDetailView.as_view(), name="detail"),
    # path('myanimals/', MyAnimalsListView.as_view(model = "Animals"), name="mylist"),
    path('', AnimalListView.as_view(), name='list'),
    path('post/<slug>/comment/', add_comment_to_post, name='add_comment_to_post')
]

apps/django_messages/urls.py
from django.conf.urls import *
from django.views.generic import RedirectView
from django.urls import path, include

from .views import *

app_name = "messages"

urlpatterns = (
    path('', RedirectView.as_view(permanent=True, url='inbox/'), name='messages_redirect'),
    path('inbox/', inbox, name='messages_inbox'),
    path('outbox/', outbox, name='messages_outbox'),
    path('compose/', compose, name='messages_compose'),
    path('compose/<recipient>/', compose, name='messages_compose_to'),
    path('reply/(<message_id>/', reply, name='messages_reply'),
    path('view/(<message_id>/', view, name='messages_detail'),
    path('delete/(<message_id>)/', delete, name='messages_delete'),
    path('undelete/(<message_id>)/', undelete, name='messages_undelete'),
    path('trash/', trash, name='messages_trash'),
)

apps/home/urls.py
from django.urls import path
from .views import Index, Home

urlpatterns = [
    path('', Index.as_view(), name="index"),
    path('home/', Home.as_view(), name="home"),
]

apps/animals/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
import datetime
from django.db.models.signals import pre_save, post_save
from .utils import unique_slug_generator
from django.shortcuts import get_object_or_404
from ..accounts.models import UserModel


class Animals(models.Model):
    DOG = "dog"
    CAT = "cat"
    MALE = "m"
    FEMALE = "f"

    ANIMAL_CHOICES = (
        (DOG, 'Dog'),
        (CAT, 'Cat'),
        
    )

    GENDER_CHOICES = (

        (MALE, "Male"),
        (FEMALE, "Female")

    )

    category = models.CharField(max_length=10, choices=ANIMAL_CHOICES, default=DOG)
    name = models.CharField(max_length=120, null=False, blank=False)
    location = models.CharField(max_length=120, null=False, blank=False)
    sex = models.CharField(choices=GENDER_CHOICES, max_length=120, null=False, blank=False)
    description = models.TextField(max_length=120, null=False, blank=False)
    photo = models.ImageField("photo", upload_to="media/", null=False, blank=False)
    timestamp = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(null=True, blank=True)
    author = models.ForeignKey(UserModel, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    @property
    def title(self):
        return self.name


def animal_pre_save_receiver(sender, instance, *args, **kwargs):
    print("saving")
    print(instance.timestamp)
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)


# def animal_post_save_receiver(sender, instance, created, *args, **kwargs):
# 		print("saved")
# 		print(instance.timestamp)


pre_save.connect(animal_pre_save_receiver, sender=Animals)


# post_save.connect(animal_post_save_receiver,  sender= Animals)


class Comment(models.Model):
    text = models.TextField(max_length=300, blank=False, null=False)
    post = models.ForeignKey('animals.Animals', related_name='comments', on_delete=models.CASCADE)
    author = models.ForeignKey("accounts.UserModel", on_delete=models.CASCADE, default=1)
    created_date = models.DateTimeField(auto_now_add=True)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.text

apps/home/models.py
from django.db import models

# Create your models here.

apps/animals/forms.py
from django import forms
from .models import Animals, Comment


# class AnimalCreate(forms.Form):

# 	name            = forms.CharField()
# 	breed           = forms.CharField()
# 	age             = forms.CharField()
# 	gender          = forms.CharField()





class AnimalCreateForm(forms.ModelForm):
	# category = forms.CharField(required= False, validators=[validate_category])
	# email = forms.EmailFi.eld()
	
	class Meta:
		model = Animals
		fields =[
		"category", 
		"name", 
		"location",
		"sex",
		"description",
		"photo",
		
		
		
		
		
		]


class CommentForm(forms.ModelForm):
	# text = TextField(max_length = 240, blank = False, null = False, default = "o")

	class Meta:
		model = Comment
		fields = ( 'text',)

apps/animals/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.template import loader
from django.http import HttpResponse
from django.views.generic import (View, ListView, DetailView, UpdateView, DeleteView, TemplateView, CreateView)
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import AnimalCreateForm
from .models import Animals, Comment
from django.urls import reverse_lazy
from django.db.models import Q
from django.views.generic.edit import FormView
from django.contrib.auth import get_user_model
from django.contrib.messages.views import SuccessMessageMixin
from .forms import CommentForm
from ..accounts.models import UserModel
from django.contrib import messages

User = get_user_model()


def add_comment_to_post(request, slug):
    template_name = "comment.html"
    post = get_object_or_404(Animals, slug=slug)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.author = request.user
            comment.save()
            messages.success(request, 'Comment succesufuly added!')
            return redirect("/home/")
    else:
        form = CommentForm()
    return render(request, template_name, {'form': form})


class AnimalCreateView(SuccessMessageMixin, FormView, LoginRequiredMixin, CreateView):
    form_class = AnimalCreateForm
    template_name = 'animals/form.html'
    success_message = 'You succesufuly added animal for adoption!'
    model = Animals

    # def get_succes_message(self, cleaned_data):
    #     print(cleaned_data)
    #     return ("You added animal succesufuly!")

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.author = self.request.user
        return super(AnimalCreateView, self).form_valid(form)

    # def form_valid(self, form):
    #     instance = form.save(commit=False)
    #     instance.user = self.request.user
    #     return super(AnimalCreateView, self).form_valid(form)


class AnimalListView(LoginRequiredMixin, ListView):
    template_name = "animals/animal_list.html"

    def get_queryset(self):
        return Animals.objects.all()


class MyAnimalsListView(LoginRequiredMixin, ListView):
    context_object_name = "animal_list"
    template_name = "animals/my_animal_list.html"

    # queryset = Animals.objects.filter(autor = request.User)
    def get_queryset(self):
        return Animals.objects.filter(author=self.request.user)


class AnimalDetailView(LoginRequiredMixin, DetailView):
    template_name = "animals/animals_detail.html"
    model = Animals

    def get_context_data(self, *args, **kwargs):
        context = super(AnimalDetailView, self).get_context_data(*args, **kwargs)
        print(context)
        # context['object'] = UserModel.objects.all(nickname = nickname)
        return context


class AnimalUpdateView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    form_class = AnimalCreateForm
    login_url = '/accounts/login/'
    template_name = 'animals/animals_update.html'
    success_message = 'You succesufuly updated your pet!'
    success_url = "/animals/mylist/"

    # success_url = "/restaurants/"

    def get_context_data(self, *args, **kwargs):
        context = super(AnimalUpdateView, self).get_context_data(*args, **kwargs)
        name = self.get_object().name
        context['title'] = f'Update animal: {name}'
        return context

    def get_queryset(self):
        return Animals.objects.filter(author=self.request.user)


class AnimalDeleteView(SuccessMessageMixin, LoginRequiredMixin, DeleteView):
    template_name = "animals/author_check_delete.html"
    model = Animals
    success_message = "You succesufuly removed animal"
    success_url = reverse_lazy("animals:list_animals")

apps/home/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.views.generic import TemplateView, ListView
from ..animals.models import Animals


class Index(TemplateView):
    login_url = "/login/"
    redirect_field_name = '/about/'
    template_name = "index.html"


class Home(LoginRequiredMixin, ListView):
    template_name = "animals/home.html"
    queryset = Animals.objects.all()

templates/animals/animal_list.html
{% include "base.html" %}

{% block content %}

{% include "animals/snippets/search.html" %}

{% for obj in object_list %}


<div class="row" style="width:320px; left:20px; display: inline-block; margin-right: 40px;">
  <div class="col s12 m4" style="width:100%;">
<div  class="card" style="width:250px">
	{% if obj.photo %}
  <img class="card-img-top" src="{{ obj.photo.url }}" alt="Card image">
    	{% else %}
    	<p> This animal has no any photos!</p>
    	{% endif %}
  <div class="card-body">
    <h4 class="card-title">Name: {{ obj.name }}</h4>
    <p class="card-text">Category: {{ obj.category }}</p>
    <p class="card-text">Location: {{ obj.location }}</p>
    <p> Added by: {{ obj.author.get_full_name }}</p> <br>
    <a href="/animals/{{ obj.slug }}/"  %}" class="btn btn-primary">More Info</a>
  </div>
</div> 
</div>
</div>







{% endfor %}

{% endblock content %}

templates/animals/animals_detail.html
{% include "base.html" %}
{% block content %}




<div> <ul> {% if animals.photo %}
<img border=" 7" src="{{animals.photo.url}}" class="img-responsive" height=" 200" alt="Smiley face">
{% else %}  

<p> This animal has no picture! </p>

            {% endif %}

<li><h1> {{animals.name}},   <small>{{animals.category}}</small></h1> </li> 
<li> <h2> Gender: {{animals.sex}} </h2> </li>
<li> <h2> Location: {{animals.location}} </h2> </li>
<li> <h2> Description:<br/> <textarea>{{animals.description}}</textarea> </h2> </li>


<p>Added by {{ animals.author.get_full_name }} </p>
<p> Created at: {{animals.timestamp}}</p>
{{ data }} <br/>

{% if user.is_authenticated %}
<p><a href="{% url 'messages:messages_compose_to' recipient=animals.author.email %}"> Ask for adoptin   </p>
	{% endif %}
{% if user.is_authenticated and user == animals.author %}
<h3> Remove animal <h3>  <a href="{% url 'animals:delete' animals.slug %}"> Delete </a> <br>

<b> Make changes </b> <br> <a href="{% url 'animals:update' animals.slug %}">Here</a>
{% endif %}


 


</ul>
</div>





<a class="btn btn-default" href="{% url 'animals:add_comment_to_post' slug=animals.slug %}">Add comment</a>
<hr>
{% for comment in animals.comments.all %}
    <div class="comment">
        <div class="date">{{ comment.text }}</div>
        <strong>Commented by:<a href="{% url 'accounts:detail' nickname=comment.author.nickname  %}"> {{ comment.author.get_full_name }} </a></strong>
        <small>Comment added: {{ comment.created_date }}</small>
        <hr>
        
    </div>
{% empty %}
    <p>No comments here yet :(</p>
{% endfor %}

<style> 
.comment {
    margin: 20px 0px 20px 20px;
}
</style>

{% endblock %}

templates/animals/animals_update.html
{% include "base.html" %}
{% block content %}
<div class='row'>
<div class='col-sm-6 col-sm-offset-3'>

<h1>{{ form.instance.title }} <small> {{ form.instance.category }}</small></h1>
<p>{{ form.instance.location }}</p>
<p>{{ form.instance.timestamp }}, Updated {{ form.instance.updated|timesince }} ago</p>

<hr/>

{{title}}

<h3>Make Changes</h3>
{% include 'animals/snippets/form_snippet.html' with form=form %}


</div>
</div>
{% endblock %}

templates/animals/author_check_delete.html
{% include "base.html" %}

{% block content %}



<div>
<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm" />
</form>
</div>

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

{% endblock content %}

templates/animals/base.html
<!DOCTYPE html>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

<html>

<style type="text/css">
	
	body {background-color: #c4ff4d;}
	div {border-bottom-color: coral;}
	p.c {
    font-style: oblique;
}
div {
    animation: mymove 5s infinite;
}
</style>

{% include "animals/snippets/nav.html" %}
{% if user.is_authenticated%}
<p align="center" class="bg-success text-white"> Hello {{ request.user.first_name }}<br>Your nickname is {{ request.user.nickname }}.  </p> <hr>
{% endif %}
<body>
{% if messages %}
<div class="alert alert-success">
    {% for m in messages %}
    <li>{{ m }}</li> <br>
    {% endfor %}
</div>
{% endif %}

</div>
</body>
</html>

templates/animals/comment.html
    <h3>New comment</h3>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Send</button>
    </form>

templates/animals/form.html
{% include "base.html" %}

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

{% block content %}
{% if form.error.non_field_errors %}
{{ form.errors.non_field_errors }}
{% endif %}

<div align="center"> <form enctype="multipart/form-data" method="POST">{% csrf_token %}
	
	{{ form.as_p }}
	<button type="submit">Save</button>


</form>
</div>

{% endblock content %}

templates/animals/home.html
{% include "base.html" %}


{% block content %}
<html>
<body>
	

<div align="center"><h2 >Add animal for adoption bellow</h2>
	<button type="button" class="button"><a href="{% url 'animals:create' %}">Add a pet</a></button>
	
	<p>OR</p>
	<h2>Find you pet friend </h2>
	<button type="button" class="button"><a href="{% url 'animals:list' %}">Find a pet</a></button>
	



 
  </div>

</body>
</html>
{% endblock content %}

templates/animals/index.html
{% block content %}
<body bgcolor="#c4ff4d">
<div align="center"><h1>Welcome!




</h1>
<p>This is a place for animal adoption.Please Log in to continue</p>

<a href="{% url 'accounts:login' %}">Login here</a>


<p> Or Register: </p>



<a href="{% url 'accounts:register' %}">Register</a>




</div>


</html>
</body>
{% endblock content %}

templates/animals/my_animal_list.html
{% include "base.html" %}

{% block content %} 

{% if animal_list %}


<ul><h2> Hello {{ user.first_name  }}, this is list of animals that you added for adoption: </h2>

{% for object in animal_list %}
<div class="row" style="width:320px; left:20px; display: inline-block; margin-right: 40px;">
  <div class="col s12 m4" style="width:100%;">
<div class="card" style="width:300px">
	{% if object.photo %}
  <img class="card-img-top" src="{{ object.photo.url }}" alt="Card image">
    	{% else %}
    	<p> This animal has no any photos!</p>
    	{% endif %}
  <div class="card-body">
    <h4 class="card-title">Name: {{ object.name }}</h4>
    <p class="card-text">Category: {{ object.category }}</p>
    <p class="card-text">Location: {{ object.location }}</p>
    <p> Added by: {{ object.author.get_full_name }} <br>
    <a href="/animals/{{ object.slug }}/"  %}" class="btn btn-primary">More Info</a>
  </div>
</div>
</div>
</div>
{% endfor %}

{% else %}

<div align=" center">
<h3> Seems like you didnt add any animal. What are you waiting for?</h3>

<a href="{% url 'animals:create' %}">
    <button>Create animal</button>
</a>
</div>
{% endif %}
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}


{% endblock content %}

templates/animals/profile_detail.html
{% include "base.html" %}



{% block content %}

{{ user.first_name }}
{{ user.last_name }}

{% endblock content %}